---
# Avant d'ajouter une collection dans ce fichier, vérifier qu'elle ne soit pas déjà installée avec Ansible
# avec la commande "ansible-galaxy collection list"
collections:
  - name: juniper.device
    version: "2.0.1"

  # # Installed with ansible
  # # Provide 'ansible.utils.ipaddr' filter used in
  # # - insa_strasbourg.juniper/roles/ex_config/templates/juniper.conf.j2
  # # - insa_strasbourg.juniper/roles/ex_config/templates/juniper-els.conf.j2
  # - name: ansible.utils
  #   version: ">=6.0.1"
